"""create initial and gamification tables

Revision ID: b454ea40d59b
Revises: 
Create Date: 2026-04-08 22:28:52.825982

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'b454ea40d59b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS users (
            id UUID NOT NULL PRIMARY KEY,
            email VARCHAR(255) NOT NULL,
            full_name VARCHAR(255),
            hashed_password VARCHAR(255),
            is_active BOOLEAN NOT NULL,
            is_oauth_user BOOLEAN NOT NULL
        )
        """
    )
    op.execute("CREATE UNIQUE INDEX IF NOT EXISTS ix_users_email ON users (email)")

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS course_progress (
            id SERIAL NOT NULL PRIMARY KEY,
            user_id UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
            module_key VARCHAR(100) NOT NULL,
            unlocked BOOLEAN NOT NULL
        )
        """
    )
    op.execute(
        "CREATE INDEX IF NOT EXISTS ix_course_progress_user_id ON course_progress (user_id)"
    )

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS daily_streaks (
            user_id UUID NOT NULL PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
            last_activity_date DATE NOT NULL
        )
        """
    )

    op.execute(
        """
        CREATE TABLE IF NOT EXISTS user_stats (
            user_id UUID NOT NULL PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
            total_xp INTEGER NOT NULL,
            current_level INTEGER NOT NULL,
            longest_streak INTEGER NOT NULL
        )
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_stats')
    op.drop_table('daily_streaks')
    op.drop_index(op.f('ix_course_progress_user_id'), table_name='course_progress')
    op.drop_table('course_progress')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
